const SOCKET_NEW_USER_CONNECTED = 'USER_CONNECTED';
const SOCKET_USER_DISCONNECTED = 'USER_DISCONNECTED';
const SOCKET_USERS = 'USERS';
const SOCKET_PRIVATE_MESSAGE = 'PRIVATE_MESSAGE';
const SOCKET_USER_IS_TYPING = 'USER_IS_TYPING';

// base
const SOCKET_CONNECTION = 'CONNECTION';
const SOCKET_DISCONNECT = 'DISCONNECT';
const SOCKET_SESSION_STARTED = 'SESSION';

// webRTC
const PRE_OFFER = 'PRE_OFFER';
const JOIN_TO_THE_CALL = 'JOIN_TO_THE_CALL';

module.exports = {
  SOCKET_NEW_USER_CONNECTED,
  SOCKET_USER_DISCONNECTED,
  SOCKET_SESSION_STARTED,
  SOCKET_PRIVATE_MESSAGE,
  SOCKET_CONNECTION,
  SOCKET_DISCONNECT,
  SOCKET_USERS,
  SOCKET_USER_IS_TYPING,
  PRE_OFFER,
  JOIN_TO_THE_CALL,
};
